/*
 * Copyright (C) 2007 The Guava Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.common.base;

import com.google.common.annotations.GwtCompatible;
import java.util.Arrays;
import org.jspecify.annotations.Nullable;

/**
 * Helper functions that can operate on any {@code Object}. These methods provide null-safe
 * implementations of common operations like equality testing and hash code generation.
 *
 * <p>Most methods in this class are now superseded by their equivalents in
 * {@link java.util.Objects}, which was introduced in Java 7. New code should prefer the
 * standard library versions.
 *
 * <p>See the Guava User Guide on <a
 * href="https://github.com/google/guava/wiki/CommonObjectUtilitiesExplained">writing {@code Object}
 * methods with {@code Objects}</a>.
 *
 * @author Laurence Gonsalves
 * @since 2.0
 */
@GwtCompatible
public final class Objects extends ExtraObjectsMethodsForWeb {

  /**
   * Determines whether two possibly-null objects are equal. Returns:
   *
   * <ul>
   *   <li>{@code true} if {@code a} and {@code b} are both null.
   *   <li>{@code true} if {@code a} and {@code b} are both non-null and they are equal according to
   *       {@link Object#equals(Object)}.
   *   <li>{@code false} in all other situations.
   * </ul>
   *
   * <p>This assumes that any non-null objects passed to this function conform to the {@code
   * equals()} contract.
   *
   * <p><b>Note:</b> this method is now unnecessary and should be treated as deprecated; use {@link
   * java.util.Objects#equals} instead.
   */
  /**
   * {@inheritDoc}
   *
   * <p>This null-safe equality check avoids the common pitfall of calling
   * {@code a.equals(b)} when {@code a} might be null. Both arguments may be null.
   *
   * @param a the first object reference, may be null
   * @param b the second object reference, may be null
   * @return {@code true} if both are null or both are equal according to {@code equals()}
   */
  @SuppressWarnings("InlineMeSuggester") // would introduce fully qualified references to Objects
  public static boolean equal(@Nullable Object a, @Nullable Object b) {
    return java.util.Objects.equals(a, b);
  }

  /**
   * Generates a hash code for multiple values. The hash code is generated by calling {@link
   * Arrays#hashCode(Object[])}. Note that array arguments to this method, with the exception of a
   * single Object array, do not get any special handling; their hash codes are based on identity
   * and not contents.
   *
   * <p>This is useful for implementing {@link Object#hashCode()}. For example, in an object that
   * has three properties, {@code x}, {@code y}, and {@code z}, one could write:
   *
   * {@snippet :
   * public int hashCode() {
   *   return Objects.hashCode(getX(), getY(), getZ());
   * }
   * }
   *
   * <p><b>Warning:</b> When a single object is supplied, the returned hash code does not equal the
   * hash code of that object.
   *
   * <p><b>Note:</b> this method is now unnecessary and should be treated as deprecated; use {@link
   * java.util.Objects#hash} instead.
   */
  @SuppressWarnings("InlineMeSuggester") // would introduce fully qualified references to Objects
  public static int hashCode(@Nullable Object @Nullable ... objects) {
    return java.util.Objects.hash(objects);
  }

  /**
   * Returns the first of two given parameters that is not {@code null}, if either is,
   * or otherwise throws a {@link NullPointerException}.
   *
   * <p><b>Note:</b> this method is now unnecessary and should be treated as deprecated;
   * use {@link java.util.Objects#requireNonNullElse} (Java 9+) instead.
   *
   * @param first the first value to check
   * @param second the second value to check
   * @return {@code first} if it is non-null; otherwise {@code second} if it is non-null
   * @throws NullPointerException if both {@code first} and {@code second} are null
   * @since 23.1
   */
  public static <T> T firstNonNull(@Nullable T first, @Nullable T second) {
    if (first != null) {
      return first;
    }
    if (second != null) {
      return second;
    }
    throw new NullPointerException("Both arguments to firstNonNull were null");
  }

  private Objects() {}
}
